Creating a Logistic Regression to Predict Absenteeism

In [1]:
#import libraries

In [2]:
import pandas as pd
import numpy as np

In [3]:
data_preprocessed = pd.read_csv('Absenteeism_preprocessed.csv')

In [4]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4        Date  Transportation Expense  \
0         0         0         0         1  2015-07-07                     289   
1         0         0         0         0  2015-07-14                     118   
2         0         0         0         1  2015-07-15                     179   
3         1         0         0         0  2015-07-16                     279   
4         0         0         0         1  2015-07-23                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          0   
1                13   50                  239.554               31          0   
2                51   38                  239.554               31          0   
3                 5   39                  239.554               24          0   
4                36   33                  239.554               30          0   

   Children  Pets  Absenteeism Time in Hours  Month Value  Day of the Week  
0         2     1                          4            7                1  
1         1     0                          0            7                1  
2         0     0                          2            7                2  
3         2     0                          4            7                3  
4         2     1                          2            7                3

Create the Targets

In [5]:
#Logistic Regression

In [6]:
# Create two classes- people excessively absent and moderately absent

In [7]:
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [8]:
# </= 3 is moderately absent

In [9]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > 
                   data_preprocessed['Absenteeism Time in Hours'].median(), 1, 0)

In [10]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [11]:
data_preprocessed['Excessive Absenteeism'] = targets

In [12]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4        Date  Transportation Expense  \
0         0         0         0         1  2015-07-07                     289   
1         0         0         0         0  2015-07-14                     118   
2         0         0         0         1  2015-07-15                     179   
3         1         0         0         0  2015-07-16                     279   
4         0         0         0         1  2015-07-23                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          0   
1                13   50                  239.554               31          0   
2                51   38                  239.554               31          0   
3                 5   39                  239.554               24          0   
4                36   33                  239.554               30          0   

   Children  Pets  Absenteeism Time in Hours  Month Value  Day of the Week  \
0         2     1                          4            7                1   
1         1     0                          0            7                1   
2         0     0                          2            7                2   
3         2     0                          4            7                3   
4         2     1                          2            7                3   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [13]:
# using median is numerically stable 

In [14]:
targets.sum() / targets.shape[0]

0.45571428571428574

In [15]:
# around 46% of targets are ones
# balance of 45-55 is almost always sufficient

In [16]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours','Day of the Week', 'Daily Work Load Average', 'Distance to Work'], axis=1)

In [17]:
data_with_targets is data_preprocessed

False

In [18]:
data_with_targets.head()

Reason_1  Reason_2  Reason_3  Reason_4        Date  Transportation Expense  \
0         0         0         0         1  2015-07-07                     289   
1         0         0         0         0  2015-07-14                     118   
2         0         0         0         1  2015-07-15                     179   
3         1         0         0         0  2015-07-16                     279   
4         0         0         0         1  2015-07-23                     289   

   Age  Body Mass Index  Education  Children  Pets  Month Value  \
0   33               30          0         2     1            7   
1   50               31          0         1     0            7   
2   38               31          0         0     0            7   
3   39               24          0         2     0            7   
4   33               30          0         2     1            7   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

Select Inputs for Regression

In [19]:
data_with_targets.shape

data_with_targets = data_with_targets.drop(['Date'], axis=1)

In [20]:
data_with_targets.iloc[:, 0:14]

Reason_1  Reason_2  Reason_3  Reason_4  Transportation Expense  Age  \
0           0         0         0         1                     289   33   
1           0         0         0         0                     118   50   
2           0         0         0         1                     179   38   
3           1         0         0         0                     279   39   
4           0         0         0         1                     289   33   
..        ...       ...       ...       ...                     ...  ...   
695         1         0         0         0                     179   40   
696         1         0         0         0                     225   28   
697         1         0         0         0                     330   28   
698         0         0         0         1                     235   32   
699         0         0         0         1                     291   40   

     Body Mass Index  Education  Children  Pets  Month Value  \
0                 30          0         2     1            7   
1                 31          0         1     0            7   
2                 31          0         0     0            7   
3                 24          0         2     0            7   
4                 30          0         2     1            7   
..               ...        ...       ...   ...          ...   
695               22          1         2     0            5   
696               24          0         1     2            5   
697               25          1         0     0            5   
698               25          1         0     0            5   
699               25          0         1     1            5   

     Excessive Absenteeism  
0                        1  
1                        0  
2                        0  
3                        1  
4                        0  
..                     ...  
695                      1  
696                      0  
697                      1  
698                      0  
699                      0  

[700 rows x 12 columns]

In [21]:
data_with_targets.iloc[:, :-1]

Reason_1  Reason_2  Reason_3  Reason_4  Transportation Expense  Age  \
0           0         0         0         1                     289   33   
1           0         0         0         0                     118   50   
2           0         0         0         1                     179   38   
3           1         0         0         0                     279   39   
4           0         0         0         1                     289   33   
..        ...       ...       ...       ...                     ...  ...   
695         1         0         0         0                     179   40   
696         1         0         0         0                     225   28   
697         1         0         0         0                     330   28   
698         0         0         0         1                     235   32   
699         0         0         0         1                     291   40   

     Body Mass Index  Education  Children  Pets  Month Value  
0                 30          0         2     1            7  
1                 31          0         1     0            7  
2                 31          0         0     0            7  
3                 24          0         2     0            7  
4                 30          0         2     1            7  
..               ...        ...       ...   ...          ...  
695               22          1         2     0            5  
696               24          0         1     2            5  
697               25          1         0     0            5  
698               25          1         0     0            5  
699               25          0         1     1            5  

[700 rows x 11 columns]

In [22]:
unscaled_inputs = data_with_targets.iloc[:, :-1]

Standardize the Data

In [23]:
from sklearn.preprocessing import StandardScaler

absenteeism_scaler = StandardScaler()

In [24]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

class CustomScaler(BaseEstimator,TransformerMixin):
    
    def __init__(self,columns):
        self.scaler = StandardScaler()
        self.columns = columns

    
    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self
    
    def transform(self, X, y=None, copy=None):
        init_col_order = X.columns
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        X_not_scaled = X.loc[:,~X.columns.isin(self.columns)]
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]

In [25]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Month Value'], dtype=object)

In [26]:
#columns_to_scale = ['Month Value', 'Day of the Week',
      # 'Transportation Expense', 'Distance to Work', 'Age',
       #'Daily Work Load Average', 'Body Mass Index',
       #'Children', 'Pets']
columns_to_omit = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Education']

In [27]:
columns_to_scale = [x for x in unscaled_inputs.columns.values if x not in columns_to_omit]

In [28]:
absenteeism_scaler = CustomScaler(columns_to_scale)

In [29]:
absenteeism_scaler.fit(unscaled_inputs)

CustomScaler(columns=['Transportation Expense', 'Age', 'Body Mass Index',
                      'Children', 'Pets', 'Month Value'])

In [30]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

In [31]:
scaled_inputs

Reason_1  Reason_2  Reason_3  Reason_4  Transportation Expense       Age  \
0           0         0         0         1                1.005844 -0.536062   
1           0         0         0         0               -1.574681  2.130803   
2           0         0         0         1               -0.654143  0.248310   
3           1         0         0         0                0.854936  0.405184   
4           0         0         0         1                1.005844 -0.536062   
..        ...       ...       ...       ...                     ...       ...   
695         1         0         0         0               -0.654143  0.562059   
696         1         0         0         0                0.040034 -1.320435   
697         1         0         0         0                1.624567 -1.320435   
698         0         0         0         1                0.190942 -0.692937   
699         0         0         0         1                1.036026  0.562059   

     Body Mass Index  Education  Children      Pets  Month Value  
0           0.767431          0  0.880469  0.268487     0.182726  
1           1.002633          0 -0.019280 -0.589690     0.182726  
2           1.002633          0 -0.919030 -0.589690     0.182726  
3          -0.643782          0  0.880469 -0.589690     0.182726  
4           0.767431          0  0.880469  0.268487     0.182726  
..               ...        ...       ...       ...          ...  
695        -1.114186          1  0.880469 -0.589690    -0.388293  
696        -0.643782          0 -0.019280  1.126663    -0.388293  
697        -0.408580          1 -0.919030 -0.589690    -0.388293  
698        -0.408580          1 -0.919030 -0.589690    -0.388293  
699        -0.408580          0 -0.019280  0.268487    -0.388293  

[700 rows x 11 columns]

In [32]:
scaled_inputs.shape

(700, 11)

Split Data into Train and Test and Shuffle

Import relevant module

In [33]:
from sklearn.model_selection import train_test_split

In [34]:
#SPLIT

train_test_split(scaled_inputs, targets)

[     Reason_1  Reason_2  Reason_3  Reason_4  Transportation Expense       Age  \
 139         1         0         0         0               -0.654143  0.248310   
 267         0         0         1         0                0.190942  0.091435   
 244         1         0         0         0                1.624567 -1.320435   
 203         0         0         0         0                0.190942  1.817054   
 389         0         0         0         1               -0.654143  0.248310   
 ..        ...       ...       ...       ...                     ...       ...   
 351         0         0         0         1               -0.654143  0.248310   
 41          0         0         0         1               -1.574681  0.091435   
 619         0         0         0         1                0.387122  1.660180   
 43          0         0         1         0                0.190942  1.032682   
 26          0         0         0         1                1.005844 -0.536062   
 
      Body Mas

In [35]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, train_size = 0.8, random_state = 20)

In [36]:
print (x_train.shape, y_train.shape)

(560, 11) (560,)


In [37]:
print (x_test.shape, y_test.shape)

(140, 11) (140,)


Fitting Model and Acessing Accuracy

In [38]:
#Logistic Regression w/ Sklearn

from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [39]:
#Training the Model

reg = LogisticRegression()

In [40]:
reg.fit(x_train, y_train)

LogisticRegression()

In [41]:
reg.score(x_train, y_train)

0.7732142857142857

In [42]:
# Manually check the accuracy

In [43]:
model_outputs = reg.predict(x_train)
model_outputs

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [44]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,

In [45]:
model_outputs == y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [46]:
np.sum((model_outputs==y_train))

433

In [47]:
model_outputs.shape[0]

560

In [48]:
np.sum((model_outputs==y_train)) / model_outputs.shape[0]

0.7732142857142857

Finding Intercept and Coefficients

In [49]:
reg.intercept_

array([-1.6474549])

In [50]:
reg.coef_

array([[ 2.80019733,  0.95188356,  3.11555338,  0.83900082,  0.60528415,
        -0.16989096,  0.27981088, -0.21053312,  0.34826214, -0.27739602,
         0.1589299 ]])

In [51]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Month Value'], dtype=object)

In [52]:
feature_name = unscaled_inputs.columns.values

In [53]:
summary_table = pd.DataFrame (columns=['Feature name'], data = feature_name)

summary_table['Coefficient'] = np.transpose(reg.coef_)

summary_table

Feature name  Coefficient
0                 Reason_1     2.800197
1                 Reason_2     0.951884
2                 Reason_3     3.115553
3                 Reason_4     0.839001
4   Transportation Expense     0.605284
5                      Age    -0.169891
6          Body Mass Index     0.279811
7                Education    -0.210533
8                 Children     0.348262
9                     Pets    -0.277396
10             Month Value     0.158930

In [54]:
summary_table.index = summary_table.index + 1
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

Feature name  Coefficient
0                Intercept    -1.647455
1                 Reason_1     2.800197
2                 Reason_2     0.951884
3                 Reason_3     3.115553
4                 Reason_4     0.839001
5   Transportation Expense     0.605284
6                      Age    -0.169891
7          Body Mass Index     0.279811
8                Education    -0.210533
9                 Children     0.348262
10                    Pets    -0.277396
11             Month Value     0.158930

Interpreting the Coefficients

In [55]:
#coefficients = log(odds)


In [56]:
summary_table['Odds_ratio'] = np.exp(summary_table.Coefficient)

In [57]:
summary_table

Feature name  Coefficient  Odds_ratio
0                Intercept    -1.647455    0.192539
1                 Reason_1     2.800197   16.447892
2                 Reason_2     0.951884    2.590585
3                 Reason_3     3.115553   22.545903
4                 Reason_4     0.839001    2.314054
5   Transportation Expense     0.605284    1.831773
6                      Age    -0.169891    0.843757
7          Body Mass Index     0.279811    1.322880
8                Education    -0.210533    0.810152
9                 Children     0.348262    1.416604
10                    Pets    -0.277396    0.757754
11             Month Value     0.158930    1.172256

In [58]:
summary_table.sort_values('Odds_ratio', ascending=False)

Feature name  Coefficient  Odds_ratio
3                 Reason_3     3.115553   22.545903
1                 Reason_1     2.800197   16.447892
2                 Reason_2     0.951884    2.590585
4                 Reason_4     0.839001    2.314054
5   Transportation Expense     0.605284    1.831773
9                 Children     0.348262    1.416604
7          Body Mass Index     0.279811    1.322880
11             Month Value     0.158930    1.172256
6                      Age    -0.169891    0.843757
8                Education    -0.210533    0.810152
10                    Pets    -0.277396    0.757754
0                Intercept    -1.647455    0.192539

In [59]:
#if coeff is around 0 and odds ratio is around 1, feature is not particularly important

Standardizing only numerical variables (creating custom scaler)

In [60]:
#when we standardize variable, we also standardized dummys = bad


Interpreting Coefficients of Logistic Regression

In [61]:
#further from 0, bigger importance

Backward Elimination or How to Simplify your model

In [62]:
#Backward Elimination- remove features w/ almost no contribuiton to model
#If weight is small enough, it won't make a difference

Testing The Model

In [63]:
#once we test, we are not allowed to touch model anymore

In [64]:
reg.score(x_test,y_test)

0.75

In [65]:
#in 75% percent of the cases, the model will predict if the person is going to be excessively absent
#test accuracy is always lower than train accuracy
#if 10-20% lower, our model overfitted

In [66]:
predicted_proba = reg.predict_proba(x_test)
predicted_proba

array([[0.71340413, 0.28659587],
       [0.58724228, 0.41275772],
       [0.44020821, 0.55979179],
       [0.78159464, 0.21840536],
       [0.08410854, 0.91589146],
       [0.33487603, 0.66512397],
       [0.29984576, 0.70015424],
       [0.13103971, 0.86896029],
       [0.78625404, 0.21374596],
       [0.74903632, 0.25096368],
       [0.49397598, 0.50602402],
       [0.22484913, 0.77515087],
       [0.07129151, 0.92870849],
       [0.73178133, 0.26821867],
       [0.30934135, 0.69065865],
       [0.5471671 , 0.4528329 ],
       [0.55052275, 0.44947725],
       [0.5392707 , 0.4607293 ],
       [0.40201117, 0.59798883],
       [0.05361575, 0.94638425],
       [0.7003009 , 0.2996991 ],
       [0.78159464, 0.21840536],
       [0.42037128, 0.57962872],
       [0.42037128, 0.57962872],
       [0.24783565, 0.75216435],
       [0.74566259, 0.25433741],
       [0.51017274, 0.48982726],
       [0.85690195, 0.14309805],
       [0.20349733, 0.79650267],
       [0.78159464, 0.21840536],
       [0.

In [67]:
predicted_proba.shape

(140, 2)

In [68]:
#140 test columns
#1st columns shows probability model assigned to observation of being 0
#2nd columns shows probability model assigned to observation of being 1

#we're interested in probability of excessive absenteeism (probability of getting 1)

In [69]:
predicted_proba[:,1]

array([0.28659587, 0.41275772, 0.55979179, 0.21840536, 0.91589146,
       0.66512397, 0.70015424, 0.86896029, 0.21374596, 0.25096368,
       0.50602402, 0.77515087, 0.92870849, 0.26821867, 0.69065865,
       0.4528329 , 0.44947725, 0.4607293 , 0.59798883, 0.94638425,
       0.2996991 , 0.21840536, 0.57962872, 0.57962872, 0.75216435,
       0.25433741, 0.48982726, 0.14309805, 0.79650267, 0.21840536,
       0.36956558, 0.67906035, 0.68502567, 0.52868083, 0.21840536,
       0.53506551, 0.22147081, 0.73692105, 0.40498044, 0.60505988,
       0.21075848, 0.45224466, 0.23751292, 0.39833498, 0.82755447,
       0.56797575, 0.69113325, 0.28659587, 0.21935267, 0.2033097 ,
       0.57628256, 0.3294664 , 0.66512397, 0.26949499, 0.83321968,
       0.43491525, 0.88374612, 0.23127072, 0.33415858, 0.34432939,
       0.69909345, 0.65494263, 0.29244941, 0.79200758, 0.20750276,
       0.26840558, 0.08708566, 0.22147081, 0.73245417, 0.30530219,
       0.22147081, 0.29014408, 0.90438191, 0.46061297, 0.60174

In [70]:
#in reality, log reg models calc these prob in the background
# if prob <0.5 = 0, >0.5 = 1

Saving the Model and Preparing it for Deployment

In [71]:
#saving model = saving 'reg' object
#use Python pickle- convert python subject into character stream
#must also save absenteeism_scaler
#^separating model from training data for good

In [72]:
import pickle

In [73]:
with open('model', 'wb') as file:
    pickle.dump(reg, file)

In [74]:
with open('scaler', 'wb') as file:
    pickle.dump(absenteeism_scaler, file)

Preparing Deployment of Model through a Module

In [75]:
#storing code in module will allow us to reuse it w/o trouble

In [76]:
from absenteeism_module import *

In [77]:
pd.read_csv('Absenteeism_new_data.csv')

ID  Reason for Absence        Date  Transportation Expense  \
0   22                  27  01/06/2018                     179   
1   10                   7  04/06/2018                     361   
2   14                  23  06/06/2018                     155   
3   17                  25  08/06/2018                     179   
4   14                  10  08/06/2018                     155   
5   28                  11  11/06/2018                     225   
6   16                   7  13/06/2018                     118   
7   22                  27  13/06/2018                     179   
8   34                  26  15/06/2018                     118   
9   34                  10  20/06/2018                     118   
10  23                  22  21/06/2018                     378   
11  36                  19  21/06/2018                     118   
12  12                  19  22/06/2018                     233   
13  22                  27  22/06/2018                     179   
14   2                   0  25/06/2018                     235   
15  21                   0  28/06/2018                     268   
16  36                  19  28/06/2018                     118   
17  22                  13  28/06/2018                     179   
18  15                  28  28/06/2018                     291   
19  22                  13  02/07/2018                     179   
20  34                  25  02/07/2018                     118   
21  12                  22  05/07/2018                     233   
22  34                   8  06/07/2018                     118   
23  34                  10  11/07/2018                     118   
24  12                  22  11/07/2018                     233   
25   5                  26  11/07/2018                     235   
26  12                  19  13/07/2018                     233   
27   9                   6  16/07/2018                     228   
28  34                  28  16/07/2018                     118   
29   9                   6  17/07/2018                     228   
30   6                  22  17/07/2018                     189   
31  34                  23  18/07/2018                     118   
32  10                  22  18/07/2018                     361   
33  28                  22  18/07/2018                     225   
34  13                  13  23/07/2018                     369   
35  11                  14  24/07/2018                     289   
36   1                  11  24/07/2018                     235   
37   4                   0  24/07/2018                     118   
38   8                   0  25/07/2018                     231   
39  35                   0  27/07/2018                     179   

    Distance to Work  Age  Daily Work Load Average  Body Mass Index  \
0                 26   30                  237.656               19   
1                 52   28                  237.656               27   
2                 12   34                  237.656               25   
3                 22   40                  237.656               22   
4                 12   34                  237.656               25   
5                 26   28                  237.656               24   
6                 15   46                  275.089               25   
7                 26   30                  275.089               19   
8                 10   37                  275.089               28   
9                 10   37                  275.089               28   
10                49   36                  275.089               21   
11                13   50                  275.089               31   
12                51   31                  275.089               21   
13                26   30                  275.089               19   
14                29   48                  275.089               33   
15                11   33                  275.089               25   
16                13   50                  275.089               31   
17                2

In [78]:
model = absenteeism_model('model','scaler')

In [79]:
model.load_and_clean_data('Absenteeism_new_data.csv')

In [80]:
model.predicted_outputs()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0          0       0.0         0         1            6   
1          1       0.0         0         0            6   
2          0       0.0         0         1            6   
3          0       0.0         0         1            6   
4          1       0.0         0         0            6   
5          1       0.0         0         0            6   
6          1       0.0         0         0            6   
7          0       0.0         0         1            6   
8          0       0.0         0         1            6   
9          1       0.0         0         0            6   
10         0       0.0         0         1            6   
11         0       0.0         1         0            6   
12         0       0.0         1         0            6   
13         0       0.0         0         1            6   
14         0       0.0         0         0            6   
15         0       0.0         0         0            6   
16         0       0.0         1         0            6   
17         1       0.0         0         0            6   
18         0       0.0         0         1            6   
19         1       0.0         0         0            7   
20         0       0.0         0         1            7   
21         0       0.0         0         1            7   
22         1       0.0         0         0            7   
23         1       0.0         0         0            7   
24         0       0.0         0         1            7   
25         0       0.0         0         1            7   
26         0       0.0         1         0            7   
27         1       0.0         0         0            7   
28         0       0.0         0         1            7   
29         1       0.0         0         0            7   
30         0       0.0         0         1            7   
31         0       0.0         0         1            7   
32         0       0.0         0         1            7   
33         0       0.0         0         1            7   
34         1       0.0         0         0            7   
35         1       0.0         0         0            7   
36         1       0.0         0         0            7   
37         0       0.0         0         0            7   
38         0       0.0         0         0            7   
39         0       0.0         0         0            7   

    Transportation Expense  Age  Body Mass Index  Education  Children  Pets  \
0                      179   30               19          1         0     0   
1                      361   28               27          0         1     4   
2                      155   34               25          0         2     0   
3                      179   40               22          1         2     0   
4                      155   34               25          0         2     0   
5                      225   28               24          0         1     2   
6                      118   46               25          0         2     0   
7                      179   30               19          1         0     0   
8                      118   37               28          0         0     0   
9                      118   37               28          0         0     0   
10                     378   36               21          0         2     4   
11                     118   50               31          0         1     0   
12                     233   31               21          1         1     8   
13                     179   30               19          1         0     0   
14                     235   48               33          0         1     5   
15                     268   33               25          1         0     0   
16                     118   50               31          0         1     0   
17                     179   30               19          1         0     0   
18                     291   40               25          0         1     1   
19  

In [81]:
from absenteeism_module import *
model = absenteeism_model('model','scaler')

model.load_and_clean_data('Absenteeism_new_data.csv')

model.predicted_outputs()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0          0       0.0         0         1            6   
1          1       0.0         0         0            6   
2          0       0.0         0         1            6   
3          0       0.0         0         1            6   
4          1       0.0         0         0            6   
5          1       0.0         0         0            6   
6          1       0.0         0         0            6   
7          0       0.0         0         1            6   
8          0       0.0         0         1            6   
9          1       0.0         0         0            6   
10         0       0.0         0         1            6   
11         0       0.0         1         0            6   
12         0       0.0         1         0            6   
13         0       0.0         0         1            6   
14         0       0.0         0         0            6   
15         0       0.0         0         0            6   
16         0       0.0         1         0            6   
17         1       0.0         0         0            6   
18         0       0.0         0         1            6   
19         1       0.0         0         0            7   
20         0       0.0         0         1            7   
21         0       0.0         0         1            7   
22         1       0.0         0         0            7   
23         1       0.0         0         0            7   
24         0       0.0         0         1            7   
25         0       0.0         0         1            7   
26         0       0.0         1         0            7   
27         1       0.0         0         0            7   
28         0       0.0         0         1            7   
29         1       0.0         0         0            7   
30         0       0.0         0         1            7   
31         0       0.0         0         1            7   
32         0       0.0         0         1            7   
33         0       0.0         0         1            7   
34         1       0.0         0         0            7   
35         1       0.0         0         0            7   
36         1       0.0         0         0            7   
37         0       0.0         0         0            7   
38         0       0.0         0         0            7   
39         0       0.0         0         0            7   

    Transportation Expense  Age  Body Mass Index  Education  Children  Pets  \
0                      179   30               19          1         0     0   
1                      361   28               27          0         1     4   
2                      155   34               25          0         2     0   
3                      179   40               22          1         2     0   
4                      155   34               25          0         2     0   
5                      225   28               24          0         1     2   
6                      118   46               25          0         2     0   
7                      179   30               19          1         0     0   
8                      118   37               28          0         0     0   
9                      118   37               28          0         0     0   
10                     378   36               21          0         2     4   
11                     118   50               31          0         1     0   
12                     233   31               21          1         1     8   
13                     179   30               19          1         0     0   
14                     235   48               33          0         1     5   
15                     268   33               25          1         0     0   
16                     118   50               31          0         1     0   
17                     179   30               19          1         0     0   
18                     291   40               25          0         1     1   
19  

In [2]:
# #Exporting Obtained Data set as a csv

# model.predicted_outputs().to_csv('Absenteeism_predictions.csv', index = False)